### ISSUE TITLE
split_fasta  -  do not include comment following chr into output filename 

### ISSUE THREAD

**Issue by prins101** [fls-bioinformatics-core/genomics#3]
Some fasta files include additional info following the chromosome separator.   These can cause problems for downstream tools if included in the output filename for the chromosome.

**Comment by pjbriggs** [comment]
@prins101 apologies for the delay in responding to this issue, I haven't been checking the issues list.

I'll look into this, however it would also help if you could give me an example of the sort of lines that you've encountered causing this problem - the wikipedia page at http://en.wikipedia.org/wiki/FASTA_format gives a number of different examples.

**Comment by prins101** [comment]
Hi Peter - this was some time ago, so my recollection maybe remiss.   I think I used your code to split the chromosome sequences from a single genome into their own individual files.  The genome sequence will be something like a line starting with  ">chr1" followed by many lines of sequence then a line starting with ">chr2", etc.

As you see from the FASTA format, a description is allowed following the sequence name (e.g. chr1 in this case) in a line starting with ">".  My recollection is that your code created a file for each sequence name that also included the optional description.  My sense was that this should not be part of the filename.

Hope this helps.

**Comment by pjbriggs** [comment]
@prins101 Thanks for the additional information. There seem to be a variety of different formats for the FASTA "defline" (i.e. the lines that start with `>...`), so perhaps the easiest things to do are:

1. Split the defline on spaces and only use the first part for the file name
    e.g. for `>MCHU - Calmodulin - Human, rabbit, bovine, rat, and chicken` just use `MCHU`

2. Escape any special characters found in the putative file name
    e.g. for `>gi|5524211|gb|AAD44166.1| cytochrome b [Elephas maximus maximus]` use `gi_5524211_gb_AAD44155`

3. If this results in non-unique names for the files then append some identifier to indicate it's the second, third etc version.

**Comment by pjbriggs** [comment]
This should be fixed in commit 7246dfce (currently in the `devel` branch) - will be merged into `master` next time I do an update.
