### ISSUE TITLE
Update bcftbx/cmdparse module to use argparse as a backend

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/genomics#46]
The `bcftbx/cmdparse` module is currently based on the deprecated `optparse` Python library, however this is not available in Python 3.

As part of migrating to Python 3, it would be useful to update this module to use the `argparse` library as a backend. Initially this could be provided as an explicit alternative to `optparse` (later perhaps the `optparse` backend could be swapped out entirely).

**Comment by mohit2agrawal** [comment]
Hi there!!
I just created a PR (#54) for this.
The CI fails because the tests are written for optparse.
Should I change the tests as well?

**Comment by pjbriggs** [comment]
Hello @mohit2agrawal 

Thanks for submitting PR #54 with updates to start implementing this - I really appreciate the time and effort you've taken to look into this.

Unfortunately there is currently one major issue with the straight swap of `argparse` for `optparse`: there is dependent code in another repository (https://github.com/fls-bioinformatics-core/auto_process_ngs) which uses the `cmdparse` module and expects the subparsers to be based on `optparse` (this is flagged as an issue there: https://github.com/fls-bioinformatics-core/auto_process_ngs/issues/105).

The straight swap will break this dependent project in a similar way to the CI tests, due to differences between `optparse` and `argparse`. For example:

* In `argparse` the `add_argument` method is used to define new arguments; in `optparse`, `add_option` is used.
* In `argparse`, the `parse_args()` method returns a single `Namespace` object; in `optparse` it returns an `(options, args)` tuple.

So my own plan had been to begin by enabling different subparser "backends" (either `optparse` or `argparse`) to be used. The simplest approach would be to add something like e.g.

    class CommandParser:
       ...
       def __init__(self,description=None,version=None,subparser=None):
          ...
          if subparser is None:
              subparser = optparse.OptionParser
          self._subparser = subparser
          ...
      def add_command(self,cmd,help=None,**args):
          ...
          p = self._subparser(**args)
          ...

So this would generate `optparse` subparsers by default, but could be explicitly made to use `argparse` by invoking e.g.

    p = CommandParser(subparser=argparse.ArgumentParser)

(An implementation along these lines should mean that the existing unit tests would pass, indicating that the default behaviour is unchanged; a second parallel set of unit tests would be required to test the `argparse`-based subparser.)

This intermediate approach would enable me to update the dependent project when I have more time (and the default `optparse` backend could be switched out for `argparse` once that's done).

Hopefully this makes sense. I don't know if it's something that you'd be prepared to looking at as part of your PR. Either way once again, thanks for taking the time to look at this and submit the changes.

**Comment by pjbriggs** [comment]
Hello again @mohit2agrawal I noticed that the `add_nprocessors_option`, `add_runner_option`, `add_no_save_option`, `add_dry_run_option` and `add_debug_option` functions will also need updating depending on the subparser backend.

**Comment by pjbriggs** [comment]
An update on this issue for future reference: I see this as a multi-step process:

1. **Enable `argparse` to be used as an alternative parser backend in the `cmdparse` module**
    Done thanks to PRs (#54 and #55)

2. **Projects using `cmdparse` migrate to using `argparse`**
    E.g. as in https://github.com/fls-bioinformatics-core/auto_process_ngs/issues/105

3. **Drop support for `optparse` from `cmdparse`**
    This can happen once step 2 is done.

**Comment by pjbriggs** [comment]
PR #54/#55 has a bug in the functions for handling standard arguments (e.g. `add_nprocessors_option`), if the supplied parser is actually an instance of `optparse.OptionGroup` - then the `add_arg` function (in `cmdparse.py`) doesn't recognise the subparser class.

**Comment by pjbriggs** [comment]
Update in PR #99 should address this issue.
